services:
  ######################################################
  # R Core
  ######################################################
  r-core:
    image: r/core:4.0.2
    build:
      context: ./
      dockerfile: ./.dev/docker/r-core/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_core
    restart: "no"
  ######################################################
  # R Development
  ######################################################
  r-develop:
    image: r/core:4.0.2
    build:
      context: ./
      dockerfile: ./.dev/docker/r-core/Dockerfile
    entrypoint: '/init'
    container_name: r_develop
    #working_dir: "/home/rstudio/rproject/"
    volumes:
      - ".:/home/rstudio/rproject/"
    ports:
      - 8787:8787
    restart: "no"
    environment:
      - DISABLE_AUTH=true
    stdin_open: true
    tty: true
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: r/test:4.0.2
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_test
    restart: "no"
    depends_on:
      - r-core
    stdin_open: true
    tty: true
  ######################################################
version: "3.8"
networks:
  default:
    name: r-project
