services:
  ######################################################
  # R Core
  ######################################################
  r-core:
    image: r/core:4.0.0
    build:
      context: ./
      dockerfile: ./.app/docker/r-core/Dockerfile
      args:
        - R_REPOS='https://mran.microsoft.com/snapshot/2020-04-24'
    container_name: rstudio
    volumes:
      - "./:/home/rstudio/rproject"
    ports:
      - 8787:8787
    restart: "no"
  ######################################################
version: "3.8"
networks:
  default:
    name: r-project
