version: "3.8"
services:
  ######################################################
  # R
  ######################################################
  r-ver:
    image: r-package-development:4.0.0
    build:
      context: ./
      dockerfile: ./.app/docker/r/Dockerfile
      args:
        - R_REPOS='https://mran.microsoft.com/snapshot/2020-04-24'
    container_name: r-package-test-rig
    restart: always
networks:
  default:
    name: r-ver
